export type IconCard = {
  id: string;
  title: string;
  subject: string;
  text: string;
  credit: string;
};

export const iconCards = {
  christ: {
    id: "christ",
    title: "Christ Pantocrator",
    subject: "Sinai Christ",
    text: "The 6th-century encaustic icon from Saint Catherine’s Monastery. Christ raises a hand in blessing and holds the Gospel, the image that anchors the south side of a Byzantine iconostas.",
    credit: "Public domain. Wikimedia Commons, File:Christ Icon Sinai 6th century.jpg.",
  },
  theotokos: {
    id: "theotokos",
    title: "Theotokos of Vladimir",
    subject: "Mother of God",
    text: "The Virgin holds the Christ child cheek to cheek. On the iconostas she stands north of the Royal Doors, opposite Christ.",
    credit: "CC0. Wikimedia Commons, File:Theotokos of Vladimir.jpg.",
  },
  forerunner: {
    id: "forerunner",
    title: "St. John the Forerunner",
    subject: "John the Baptist",
    text: "John, called the Forerunner, is the prophet who points to Christ. His panel stands further south of the Royal Doors, and again among the prophets of the drum.",
    credit: "Public domain. Wikimedia Commons, File:An early byzantine icon of John the Baptist, 6th century AD.jpg.",
  },
  nicholas: {
    id: "nicholas",
    title: "St. Nicholas",
    subject: "Holy hierarch",
    text: "Nicholas of Myra is the usual patron on the north side of a Ruthenian iconostas, and one of the bishops painted below the Platytera in the apse.",
    credit: "Public domain. Wikimedia Commons, File:St Nicholas Icon Sinai 13th century.jpg.",
  },
  annunciation: {
    id: "annunciation",
    title: "The Annunciation",
    subject: "Ustyug Annunciation",
    text: "Gabriel speaks to the Theotokos. The Royal Doors split this 12th-century icon: Gabriel on the north leaf, the Virgin on the south.",
    credit: "Public domain. Wikimedia Commons, File:Annunciation ystuj.jpg. Tretyakov Gallery.",
  },
  supper: {
    id: "supper",
    title: "The Mystical Supper",
    subject: "Last Supper",
    text: "Christ and the apostles at table. This panel sits directly above the Royal Doors, over the entrance to the sanctuary.",
    credit: "Public domain. Wikimedia Commons, File:Last Supper Greek Icon.tif.",
  },
  trinity: {
    id: "trinity",
    title: "The Hospitality of Abraham",
    subject: "Rublev’s Trinity",
    text: "Three angels seated at Abraham’s table, the icon the Church reads as an image of the Trinity. It hangs in the feast tier.",
    credit: "Public domain. Wikimedia Commons, File:Andrej Rublëv 001.jpg.",
  },
  nativity: {
    id: "nativity",
    title: "The Nativity of Christ",
    subject: "Feast of the Nativity",
    text: "One of the Twelve Great Feasts. The Virgin, the child in the manger, and the hillside of Bethlehem. A copy also stands on the tetrapod as the festal icon.",
    credit: "Public domain. See ATTRIBUTION.md, Nativity.",
  },
  transfiguration: {
    id: "transfiguration",
    title: "The Transfiguration",
    subject: "Feast of the Transfiguration",
    text: "Christ in light on Tabor, with Moses and Elijah, and the apostles fallen below. One of the Twelve Great Feasts along the nave.",
    credit: "Public domain. See ATTRIBUTION.md, Transfiguration.",
  },
  michael: {
    id: "michael",
    title: "Archangel Michael",
    subject: "Angel",
    text: "Michael guards the south deacon door and is repeated in the drum, among the angels that circle the Pantocrator.",
    credit: "Public domain. See ATTRIBUTION.md, Archangel Michael.",
  },
  gabriel: {
    id: "gabriel",
    title: "Archangel Gabriel",
    subject: "Angel",
    text: "Gabriel stands at the north deacon door and in the drum. He is the angel of the Annunciation.",
    credit: "Public domain. See ATTRIBUTION.md, Archangel Gabriel.",
  },
  pantocrator: {
    id: "pantocrator",
    title: "Christ Pantocrator",
    subject: "Dome, Daphni",
    text: "Christ looks down from the dome, the ruler of all, as in the mosaic at Daphni. Angels and prophets stand in the drum beneath him.",
    credit: "Public domain. Wikimedia Commons, the Daphni Pantocrator. See ATTRIBUTION.md.",
  },
  platytera: {
    id: "platytera",
    title: "The Platytera",
    subject: "Virgin of the apse",
    text: "The Virgin orans with the child, wider than the heavens, fills the apse above the Communion of the Apostles.",
    credit: "Public domain. Hagia Sophia apse mosaic. See ATTRIBUTION.md.",
  },
  deesis: {
    id: "deesis",
    title: "Deesis and the Great Feasts",
    subject: "Twelve Great Feasts",
    text: "Christ enthroned between the Virgin and the Forerunner, with the Twelve Great Feasts around them. The same panel is set high on the iconostas and along the nave.",
    credit: "Public domain. Wikimedia Commons, File:The Deesis and the Twelve Great Feasts.tif.",
  },
  cefalu: {
    id: "cefalu",
    title: "Christ Pantocrator",
    subject: "Cefalù mosaic",
    text: "The 12th-century mosaic of Christ blessing, from the apse at Cefalù. Here it is painted high in the drum, under the dome.",
    credit: "Public domain. Wikimedia Commons, File:Master of Cefalu 001 Christ Pantocrator adjusted.JPG.",
  },
  communionBread: {
    id: "communion-bread",
    title: "Communion of the Apostles",
    subject: "Christ gives the bread",
    text: "Christ gives the bread to the apostles. In a painted apse this scene sits under the Platytera, just above the hierarchs.",
    credit: "Public domain. Wikimedia Commons, File:Eucharisty with bread (1420s, Sergiev Posad).jpg.",
  },
  communionWine: {
    id: "communion-wine",
    title: "Communion of the Apostles",
    subject: "Christ gives the cup",
    text: "Christ gives the cup. Paired with the bread, it is the Communion of the Apostles across the curve of the apse.",
    credit: "Public domain. Wikimedia Commons, File:Eucharisty with wine (1420s, Sergiev Posad).jpg.",
  },
  dormition: {
    id: "dormition",
    title: "The Dormition",
    subject: "Falling-asleep of the Theotokos",
    text: "The apostles gather around the Virgin as Christ receives her soul. The Dormition is the usual image on the west wall, facing you as you leave.",
    credit: "Public domain. Wikimedia Commons, File:Goluboe uspenie.jpg.",
  },
  matthew: {
    id: "matthew",
    title: "Matthew the Evangelist",
    subject: "Evangelist",
    text: "Matthew, shown with his Gospel. The four evangelists occupy the pendentives, the curved triangles under the dome.",
    credit: "Public domain. Wikimedia Commons, File:Matthew the Evangelist - icon.jpeg.",
  },
  mark: {
    id: "mark",
    title: "Mark the Evangelist",
    subject: "Evangelist",
    text: "Mark, on the pendentive opposite Matthew. Each evangelist is painted where the arches meet the drum.",
    credit: "Public domain. Wikimedia Commons, File:087 Mark the Evangelist Icon from Saint Paraskevi Church in Langadas.jpg.",
  },
  luke: {
    id: "luke",
    title: "Luke the Evangelist",
    subject: "Evangelist",
    text: "Luke, traditionally the painter of the Virgin. His panel is one of the four pendentives.",
    credit: "Public domain. Wikimedia Commons, File:St Luke the Evangelist.jpg.",
  },
  john: {
    id: "john",
    title: "John the Evangelist",
    subject: "Evangelist",
    text: "John, the beloved disciple, on the last pendentive. Together the four carry the dome.",
    credit: "Public domain. Wikimedia Commons, File:John the Evangelist.jpg.",
  },
  exaltation: {
    id: "exaltation",
    title: "Exaltation of the Cross",
    subject: "Great Feast",
    text: "The Cross is lifted up for the people. One of the Twelve Great Feasts painted along the nave wall.",
    credit: "Public domain. Wikimedia Commons, File:Exaltation of the Cross - Palekh icon (19 c, priv.coll).jpg.",
  },
  presentation: {
    id: "presentation",
    title: "The Meeting of the Lord",
    subject: "Presentation in the Temple",
    text: "Mary and Joseph bring the child to the Temple, and Symeon receives him. One of the Twelve Great Feasts.",
    credit: "Public domain. Wikimedia Commons, File:050 Presentation of Jesus at the Temple Icon from Saint Paraskevi Church in Langadas.jpg.",
  },
  entry: {
    id: "entry",
    title: "The Entry into Jerusalem",
    subject: "Palm Sunday",
    text: "Christ rides into the city as the crowd spreads branches. Palm Sunday, one of the Twelve Great Feasts.",
    credit: "Public domain. Wikimedia Commons, File:005 Entry into Jerusalem Icon from Saint Paraskevi Church in Langadas.jpg.",
  },
  lazarus: {
    id: "lazarus",
    title: "The Raising of Lazarus",
    subject: "Saturday of Lazarus",
    text: "Christ calls Lazarus from the tomb. It is the festal icon of the Saturday before Palm Sunday, painted here with the other feast icons.",
    credit: "Public domain. Wikimedia Commons, File:Novgorod School - The Raising of Lazarus - NG.M.02420.",
  },
  ascension: {
    id: "ascension",
    title: "The Ascension",
    subject: "Great Feast",
    text: "Christ ascends and the apostles look on with the Virgin. One of the Twelve Great Feasts on the south wall.",
    credit: "Public domain. Wikimedia Commons, File:Ascension (Candia, 15th c.).jpg.",
  },
  pentecost: {
    id: "pentecost",
    title: "Pentecost",
    subject: "Descent of the Holy Spirit",
    text: "The Spirit comes upon the apostles. This mosaic from Hosios Loukas is one of the Twelve Great Feasts.",
    credit: "Public domain. Wikimedia Commons, File:Katholikon (Hosios Loukas) - Pentecost mosaic.jpg.",
  },
  prophets: {
    id: "prophets",
    title: "Prophets",
    subject: "Elijah, Pimen, and Moses the Black",
    text: "Prophet Elijah stands with the monastic saints Pimen and Moses the Black. The drum around a Pantocrator is where prophets are painted.",
    credit: "Public domain. Wikimedia Commons, File:Prophet Elijah, Venerable Pimen the Great and Moses Murin.jpg.",
  },
} as const satisfies Record<string, IconCard>;

export type IconId = keyof typeof iconCards;
